import prompts from "prompts";
import chalk from "chalk";
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, copyFileSync, writeFileSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { checkCursorCli } from "./check-cursor.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const templatesDir = join(__dirname, "..", "templates");

export async function init() {
  console.log();
  console.log(chalk.bold("cursorbyemail") + " - Email-based conversations with Cursor agents");
  console.log(chalk.dim("─".repeat(60)));
  console.log();

  // Service selection
  const serviceAnswers = await prompts([
    {
      type: "select",
      name: "emailProvider",
      message: "Select email provider:",
      choices: [
        { title: "Resend", value: "resend", description: "Transactional email API" },
      ],
      initial: 0,
    },
    {
      type: "select",
      name: "tunnelProvider",
      message: "Select tunnel provider:",
      choices: [
        { title: "ngrok", value: "ngrok", description: "Secure tunnels to localhost" },
      ],
      initial: 0,
    },
  ]);

  if (!serviceAnswers.emailProvider || !serviceAnswers.tunnelProvider) {
    console.log(chalk.red("Setup cancelled."));
    process.exit(1);
  }

  console.log();
  console.log(chalk.bold("Environment Configuration"));
  console.log(chalk.dim("These values will be stored in your .env file"));
  console.log();

  // Environment variables prompts
  const envAnswers = await prompts([
    {
      type: "text",
      name: "CURSOR_EMAIL_TO",
      message: "Email address to receive notifications:",
      validate: (v) => v.includes("@") || "Please enter a valid email address",
    },
    {
      type: "text",
      name: "CURSOR_EMAIL_SUBJECT",
      message: "Email subject prefix:",
      initial: "Cursor agent finished",
    },
    {
      type: "password",
      name: "RESEND_API_KEY",
      message: "Resend API key (starts with re_):",
      validate: (v) => v.startsWith("re_") || "Resend API keys start with 're_'",
    },
    {
      type: "text",
      name: "RESEND_FROM",
      message: 'Sender email (e.g., "Agent <agent@domain.com>"):',
      validate: (v) => v.includes("@") || "Please enter a valid sender email",
    },
    {
      type: "text",
      name: "RESEND_REPLY_TO",
      message: 'Reply-to address for webhook (e.g., "domain@yoursubdomain.resend.app"):',
      validate: (v) => v.includes("@") || "Please enter a valid reply-to address",
    },
    {
      type: "text",
      name: "NGROK_AUTHTOKEN",
      message: "ngrok auth token (leave empty if globally configured):",
    },
  ]);

  if (!envAnswers.CURSOR_EMAIL_TO || !envAnswers.RESEND_API_KEY) {
    console.log(chalk.red("Setup cancelled."));
    process.exit(1);
  }

  const cwd = process.cwd();

  console.log();
  console.log(chalk.bold("Setting up files..."));
  console.log();

  // Create .cursor/hooks directory
  const cursorHooksDir = join(cwd, ".cursor", "hooks");
  mkdirSync(cursorHooksDir, { recursive: true });
  console.log(chalk.green("✓") + ` Created ${chalk.dim(".cursor/hooks/")}`);

  // Copy hooks.json to .cursor/hooks.json
  const hooksJsonSrc = join(templatesDir, "hooks.json");
  const hooksJsonDest = join(cwd, ".cursor", "hooks.json");
  copyFileSync(hooksJsonSrc, hooksJsonDest);
  console.log(chalk.green("✓") + ` Created ${chalk.dim(".cursor/hooks.json")}`);

  // Copy hook scripts
  const hookFiles = [
    "email-on-stop.mjs",
    "beautify-transcript-email-html.js",
  ];
  for (const file of hookFiles) {
    copyFileSync(join(templatesDir, file), join(cursorHooksDir, file));
    console.log(chalk.green("✓") + ` Created ${chalk.dim(`.cursor/hooks/${file}`)}`);
  }

  // Copy webhook server
  const webhookDest = join(cursorHooksDir, "webhook.mjs");
  copyFileSync(join(templatesDir, "webhook.mjs"), webhookDest);
  console.log(chalk.green("✓") + ` Created ${chalk.dim(".cursor/hooks/webhook.mjs")}`);

  // Generate .env file
  const envContent = `# cursorbyemail configuration
# Generated by npx cursorbyemail init

# Enable email notifications on agent finish
CURSOR_EMAIL_ON_FINISH=1

# Email recipient
CURSOR_EMAIL_TO="${envAnswers.CURSOR_EMAIL_TO}"

# Email subject prefix
CURSOR_EMAIL_SUBJECT="${envAnswers.CURSOR_EMAIL_SUBJECT}"

# Resend configuration
RESEND_API_KEY="${envAnswers.RESEND_API_KEY}"
RESEND_FROM="${envAnswers.RESEND_FROM}"
RESEND_REPLY_TO="${envAnswers.RESEND_REPLY_TO}"

# ngrok configuration (optional if globally configured)
${envAnswers.NGROK_AUTHTOKEN ? `NGROK_AUTHTOKEN="${envAnswers.NGROK_AUTHTOKEN}"` : "# NGROK_AUTHTOKEN="}

# Webhook server port
WEBHOOK_PORT=8787

# Default repository path for webhook (defaults to cwd)
DEFAULT_REPO_PATH="${cwd}"
`;

  const envPath = join(cwd, ".env");
  const envExists = existsSync(envPath);
  
  if (envExists) {
    const existingEnv = readFileSync(envPath, "utf8");
    writeFileSync(envPath, existingEnv + "\n" + envContent);
    console.log(chalk.green("✓") + ` Appended to ${chalk.dim(".env")}`);
  } else {
    writeFileSync(envPath, envContent);
    console.log(chalk.green("✓") + ` Created ${chalk.dim(".env")}`);
  }

  // Add script to package.json if it exists
  const pkgPath = join(cwd, "package.json");
  if (existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
      pkg.scripts = pkg.scripts || {};
      pkg.scripts["cursor:email-hook"] = "node .cursor/hooks/email-on-stop.mjs";
      pkg.scripts["cursor:webhook"] = "node .cursor/hooks/webhook.mjs";
      writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
      console.log(chalk.green("✓") + ` Added scripts to ${chalk.dim("package.json")}`);
    } catch (e) {
      console.log(chalk.yellow("⚠") + ` Could not update package.json: ${e.message}`);
    }
  }

  console.log();
  console.log(chalk.bold("Installing dependencies..."));
  console.log();

  // Install required dependencies
  try {
    execSync("npm install --save resend dotenv express", {
      cwd,
      stdio: "inherit",
    });
    console.log();
    console.log(chalk.green("✓") + " Dependencies installed");
  } catch (e) {
    console.log(chalk.yellow("⚠") + " Failed to install dependencies. Run manually:");
    console.log(chalk.dim("  npm install resend dotenv express"));
  }

  console.log();
  console.log(chalk.bold("Checking Cursor CLI..."));
  console.log();

  // Check Cursor CLI
  await checkCursorCli();

  // Final instructions
  console.log();
  console.log(chalk.dim("─".repeat(60)));
  console.log(chalk.bold.green("Setup complete!"));
  console.log();
  console.log("Next steps:");
  console.log();
  console.log(chalk.dim("1.") + " Configure Resend webhook to point to your ngrok URL:");
  console.log(chalk.cyan("   npx cursorbyemail start"));
  console.log();
  console.log(chalk.dim("2.") + " In Resend dashboard, add webhook endpoint:");
  console.log(chalk.dim("   https://<your-ngrok-url>/inbound/resend"));
  console.log();
  console.log(chalk.dim("3.") + " Start using Cursor - emails will be sent on agent completion");
  console.log(chalk.dim("   and replies will resume the conversation."));
  console.log();
}
